version: '2'
volumes:
  settings:
  resin-data:
networks:
  net1:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/data'
    networks:
      - net1
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  fbcp:
    image: balenablocks/fbcp
    privileged: true
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    network_mode: host
#     networks:
#       - net1
    restart: always
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80
  bluetooth:
    image: balenablocks/bluetooth:raspberrypi3  # See supported devices for other archs
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: on-failure
    labels:
      io.balena.features.dbus: 1
